name: Report
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
main: me.petterim1.report.Plugin
softdepend: ["DiscordChat"]

commands:
  report:
    description: Report a player
    usage: "/report <player> <reason>"
    permission: report.use
  reports:
    description: Show all reports
    usage: "/reports"
    permission: report.see
permissions:
  report.use:
    description: "Allows player to use /report command"
    default: true
  report.see:
    description: "Allows player to see reports"
    default: op
