name: Report
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
main: idk.plugin.report.Main

commands:
  report:
    description: Report player
    usage: "/report <player> <reason>"
    permission: report.use
  reports:
    description: Show reports
    usage: "/reports"
    permission: report.see
permissions:
  report.use:
    description: "Allows player to use /report command"
    default: true
  report.see:
    description: "Allows player to see reports"
    default: op